name: Syscom → Shopify sync

on:
  workflow_dispatch:   # ← solo corre cuando lo lanzas manualmente

# schedule:
#   - cron: '0 * * * *'   # ← quita/ comenta esto (cada hora)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci || npm i
      - run: node index.mjs
        env:
          SHOP:                 ${{ secrets.SHOP }}
          ADMIN_TOKEN:          ${{ secrets.ADMIN_TOKEN }}
          SYSCOM_CLIENT_ID:     ${{ secrets.SYSCOM_CLIENT_ID }}
          SYSCOM_CLIENT_SECRET: ${{ secrets.SYSCOM_CLIENT_SECRET }}
          SYSCOM_MODE:          ${{ secrets.SYSCOM_MODE }}
          SYSCOM_QUERY:         ${{ secrets.SYSCOM_QUERY }}
          RUN_PAGES:            ${{ secrets.RUN_PAGES }}
          SLEEP_MS:             ${{ secrets.SLEEP_MS }}
          DEBUG:               ${{ vars.DEBUG }}
          SYSCOM_ONLY_STOCK:   ${{ vars.SYSCOM_ONLY_STOCK }}
